from __future__ import annotations
import logging

logger = logging.getLogger(__name__)

import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.chart.series import SeriesLabel
from openpyxl.chart.data_source import StrRef

from telmus.core.result import ScanResult, CompareResult


class ExcelExporter:
    def __init__(self) -> None:
        self.font_name = "Calibri"
        self.font_title = Font(name=self.font_name, size=14, bold=True, color="1A1A2E")
        self.font_header = Font(name=self.font_name, size=11, bold=True, color="FFFFFF")
        self.font_data_bold = Font(name=self.font_name, size=11, bold=True)
        self.font_data = Font(name=self.font_name, size=11)
        self.font_italic = Font(
            name=self.font_name, size=9, italic=True, color="555555"
        )

        self.fill_header = PatternFill(
            start_color="1A1A2E", end_color="1A1A2E", fill_type="solid"
        )
        self.fill_alt = PatternFill(
            start_color="F5F5F5", end_color="F5F5F5", fill_type="solid"
        )
        self.fill_white = PatternFill(
            start_color="FFFFFF", end_color="FFFFFF", fill_type="solid"
        )

        self.fill_green_light = PatternFill(
            start_color="D4EDDA", end_color="D4EDDA", fill_type="solid"
        )
        self.fill_orange_light = PatternFill(
            start_color="FFF3CD", end_color="FFF3CD", fill_type="solid"
        )
        self.fill_red_light = PatternFill(
            start_color="F8D7DA", end_color="F8D7DA", fill_type="solid"
        )
        self.fill_yellow_light = PatternFill(
            start_color="FFFFE0", end_color="FFFFE0", fill_type="solid"
        )

        self.thin_side = Side(border_style="thin", color="CCCCCC")
        self.border_all = Border(
            left=self.thin_side,
            right=self.thin_side,
            top=self.thin_side,
            bottom=self.thin_side,
        )

    def _style_cell(
        self,
        cell: typing.Any,
        font: Font | None = None,
        fill: PatternFill | None = None,
        border: Border | None = None,
        alignment: Alignment | None = None,
    ) -> None:
        if font:
            cell.font = font
        if fill:
            cell.fill = fill
        if border:
            cell.border = border
        if alignment:
            cell.alignment = alignment

    def _style_range(
        self,
        ws: typing.Any,
        cell_range: str,
        font: Font | None = None,
        fill: PatternFill | None = None,
        border: Border | None = None,
        alignment: Alignment | None = None,
    ) -> None:
        for row in ws[cell_range]:
            for cell in row:
                self._style_cell(cell, font, fill, border, alignment)

    def _auto_fit_columns(self, ws: typing.Any) -> None:
        ws.freeze_panes = "A2"
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                # Check if cell is in a merged range
                is_merged = False
                for merged in ws.merged_cells.ranges:
                    if cell.coordinate in merged:
                        is_merged = True
                        break
                if is_merged:
                    continue
                val_str = str(cell.value if cell.value is not None else "")
                if len(val_str) > max_len:
                    max_len = len(val_str)
            ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

    def _val(self, v: typing.Any) -> any:
        if v is None:
            return "n/a"
        try:
            if isinstance(v, (int, float)):
                return v
            return float(v)
        except (ValueError, TypeError):
            return str(v)

    import typing

    def export(self, result: ScanResult, path: str) -> None:
        wb = Workbook()
        ws_summary = wb.active
        ws_summary.title = "Summary"

        ws_valuation = wb.create_sheet(title="Valuation")
        ws_health = wb.create_sheet(title="Health")
        ws_growth = wb.create_sheet(title="Growth")
        ws_flags = wb.create_sheet(title="Red Flags")

        # ---------------- SUMMARY SHEET ----------------
        ws_summary.views.sheetView[0].showGridLines = True

        # A1 Branding
        ws_summary.merge_cells("A1:B1")
        ws_summary["A1"] = "Generated by telmus v0.1.0"
        self._style_range(
            ws_summary,
            "A1:B1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left", vertical="center"),
        )
        ws_summary.row_dimensions[1].height = 24

        summary_rows = [
            ("Company Name", result.company),
            ("Ticker", result.ticker),
            ("Exchange", result.exchange),
            ("Scan Date", datetime.date.today().isoformat()),
            ("Scan Duration", f"{result.scan_duration_ms} ms"),
            ("Highest Concern", result.highest_concern.lower()),
        ]

        for idx, (metric, val) in enumerate(summary_rows, start=2):
            fill = self.fill_alt if idx % 2 == 1 else self.fill_white
            ws_summary.cell(row=idx, column=1, value=metric)
            ws_summary.cell(row=idx, column=2, value=val)

            self._style_cell(
                ws_summary.cell(row=idx, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            # Special fill for highest concern value cell
            if metric == "Highest Concern":
                c_val = str(val).lower()
                if "high" in c_val:
                    val_fill = self.fill_red_light
                elif "medium" in c_val:
                    val_fill = self.fill_orange_light
                else:
                    val_fill = self.fill_green_light
                self._style_cell(
                    ws_summary.cell(row=idx, column=2),
                    font=self.font_data,
                    fill=val_fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )
            else:
                self._style_cell(
                    ws_summary.cell(row=idx, column=2),
                    font=self.font_data,
                    fill=fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )

        # Analyst brief: merged in row 8-12
        ws_summary.cell(row=8, column=1, value="Analyst Brief")
        self._style_cell(
            ws_summary.cell(row=8, column=1),
            font=self.font_data_bold,
            fill=self.fill_white,
            border=self.border_all,
            alignment=Alignment(horizontal="left", vertical="top"),
        )

        ws_summary.merge_cells("B8:D12")
        ws_summary["B8"] = result.analyst_brief
        self._style_range(
            ws_summary,
            "B8:D12",
            font=self.font_data,
            fill=self.fill_white,
            border=self.border_all,
            alignment=Alignment(wrap_text=True, vertical="top"),
        )

        for r in range(8, 13):
            for c in range(2, 5):
                ws_summary.cell(row=r, column=c).border = self.border_all
                ws_summary.cell(row=r, column=c).fill = self.fill_white

        self._auto_fit_columns(ws_summary)

        # ---------------- VALUATION SHEET ----------------
        ws_valuation.views.sheetView[0].showGridLines = True
        ws_valuation.append(["Metric", "Value", "Status"])
        self._style_range(
            ws_valuation,
            "A1:C1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        pe_status = result.valuation.flag if result.valuation.flag else "ok"
        pb_status = result.valuation.flag if result.valuation.flag else "ok"
        ev_status = result.valuation.flag if result.valuation.flag else "ok"
        vs_status = "flagged" if result.valuation.vs_sector == "expensive" else "ok"

        val_data = [
            ("P/E Ratio", result.valuation.pe_ratio, pe_status),
            ("P/B Ratio", result.valuation.pb_ratio, pb_status),
            ("EV/EBITDA", result.valuation.ev_ebitda, ev_status),
            ("Sector Comparison", result.valuation.vs_sector, vs_status),
        ]

        for idx, (m, v, s) in enumerate(val_data, start=2):
            fill = self.fill_alt if idx % 2 == 1 else self.fill_white
            ws_valuation.cell(row=idx, column=1, value=m)
            ws_valuation.cell(row=idx, column=2, value=self._val(v))
            ws_valuation.cell(row=idx, column=3, value=s)

            self._style_cell(
                ws_valuation.cell(row=idx, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )
            self._style_cell(
                ws_valuation.cell(row=idx, column=2),
                font=self.font_data,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            s_fill = self.fill_red_light if s != "ok" else self.fill_green_light
            self._style_cell(
                ws_valuation.cell(row=idx, column=3),
                font=self.font_data_bold,
                fill=s_fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

        self._auto_fit_columns(ws_valuation)

        # ---------------- HEALTH SHEET ----------------
        ws_health.views.sheetView[0].showGridLines = True
        ws_health.append(["Metric", "Value", "Status"])
        self._style_range(
            ws_health,
            "A1:C1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        f_val = result.health.piotroski_f
        z_val = result.health.altman_z
        de_val = result.health.debt_to_equity
        cr_val = result.health.current_ratio
        ic_val = result.health.interest_coverage

        f_status = "weak fundamentals" if (f_val is not None and f_val < 5) else "ok"
        z_status = "distress risk" if (z_val is not None and z_val < 1.81) else "ok"
        de_status = "high leverage" if (de_val is not None and de_val > 2.0) else "ok"
        cr_status = "low liquidity" if (cr_val is not None and cr_val < 1.0) else "ok"
        ic_status = "weak coverage" if (ic_val is not None and ic_val < 1.5) else "ok"

        health_rows = [
            (
                "Piotroski F-Score",
                f_val,
                f_status,
                "* Note: 7-9 is strong, 5-6 is stable, <5 is weak",
            ),
            (
                "Altman Z-Score",
                z_val,
                z_status,
                "* Note: >2.99 is safe, 1.81-2.99 is grey zone, <1.81 is distress",
            ),
            ("Debt/Equity", de_val, de_status, None),
            ("Current Ratio", cr_val, cr_status, None),
            ("Interest Coverage", ic_val, ic_status, None),
        ]

        curr_row = 2
        for idx, (m, v, s, note) in enumerate(health_rows):
            fill = self.fill_alt if curr_row % 2 == 1 else self.fill_white

            ws_health.cell(row=curr_row, column=1, value=m)
            ws_health.cell(row=curr_row, column=2, value=self._val(v))
            ws_health.cell(row=curr_row, column=3, value=s)

            self._style_cell(
                ws_health.cell(row=curr_row, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )
            self._style_cell(
                ws_health.cell(row=curr_row, column=2),
                font=self.font_data,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            s_fill = self.fill_red_light if s != "ok" else self.fill_green_light
            self._style_cell(
                ws_health.cell(row=curr_row, column=3),
                font=self.font_data_bold,
                fill=s_fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            curr_row += 1

            if note:
                ws_health.merge_cells(
                    start_row=curr_row, start_column=1, end_row=curr_row, end_column=3
                )
                ws_health.cell(row=curr_row, column=1, value=note)
                self._style_range(
                    ws_health,
                    f"A{curr_row}:C{curr_row}",
                    font=self.font_italic,
                    fill=fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )
                curr_row += 1

        self._auto_fit_columns(ws_health)

        # ---------------- GROWTH SHEET ----------------
        ws_growth.views.sheetView[0].showGridLines = True
        ws_growth.append(["Metric", "Value", "Status"])
        self._style_range(
            ws_growth,
            "A1:C1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        rev_cagr = result.growth.revenue_cagr_3y
        pat_cagr = result.growth.pat_cagr_3y
        margin_trend = result.growth.margin_trend
        fcf_yield = result.growth.fcf_yield

        rev_status = (
            "declining revenue" if (rev_cagr is not None and rev_cagr < 0) else "ok"
        )
        pat_status = (
            "declining earnings" if (pat_cagr is not None and pat_cagr < 0) else "ok"
        )
        margin_status = (
            "declining margins"
            if (margin_trend and "declining" in margin_trend.lower())
            else "ok"
        )
        fcf_status = (
            "negative yield" if (fcf_yield is not None and fcf_yield < 0) else "ok"
        )

        growth_rows = [
            ("Revenue CAGR 3Y", rev_cagr, rev_status),
            ("PAT CAGR 3Y", pat_cagr, pat_status),
            ("Margin Trend", margin_trend, margin_status),
            ("FCF Yield", fcf_yield, fcf_status),
        ]

        for idx, (m, v, s) in enumerate(growth_rows, start=2):
            fill = self.fill_alt if idx % 2 == 1 else self.fill_white
            ws_growth.cell(row=idx, column=1, value=m)
            ws_growth.cell(row=idx, column=2, value=self._val(v))
            ws_growth.cell(row=idx, column=3, value=s)

            self._style_cell(
                ws_growth.cell(row=idx, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )
            self._style_cell(
                ws_growth.cell(row=idx, column=2),
                font=self.font_data,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            s_fill = self.fill_red_light if s != "ok" else self.fill_green_light
            self._style_cell(
                ws_growth.cell(row=idx, column=3),
                font=self.font_data_bold,
                fill=s_fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

        self._auto_fit_columns(ws_growth)

        # ---------------- RED FLAGS SHEET ----------------
        ws_flags.views.sheetView[0].showGridLines = True
        ws_flags.append(["Flag Type", "Value", "Severity"])
        self._style_range(
            ws_flags,
            "A1:C1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        if not result.red_flags:
            ws_flags.merge_cells("A2:C2")
            ws_flags["A2"] = "No red flags detected"
            self._style_range(
                ws_flags,
                "A2:C2",
                font=self.font_data_bold,
                fill=self.fill_green_light,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )
        else:
            for idx, flag in enumerate(result.red_flags, start=2):
                fill = self.fill_alt if idx % 2 == 1 else self.fill_white
                ws_flags.cell(row=idx, column=1, value=flag.type)
                ws_flags.cell(row=idx, column=2, value=self._val(flag.value))
                ws_flags.cell(row=idx, column=3, value=flag.severity)

                self._style_cell(
                    ws_flags.cell(row=idx, column=1),
                    font=self.font_data_bold,
                    fill=fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )
                self._style_cell(
                    ws_flags.cell(row=idx, column=2),
                    font=self.font_data,
                    fill=fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )

                sev = str(flag.severity).lower()
                if "high" in sev:
                    s_fill = self.fill_red_light
                elif "medium" in sev:
                    s_fill = self.fill_orange_light
                else:
                    s_fill = self.fill_yellow_light
                self._style_cell(
                    ws_flags.cell(row=idx, column=3),
                    font=self.font_data_bold,
                    fill=s_fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )

        self._auto_fit_columns(ws_flags)

        # ---------------- DASHBOARD SHEET ----------------
        # index=0 makes it the first sheet in the workbook
        ws_dash = wb.create_sheet(title="Dashboard", index=0)
        ws_dash.views.sheetView[0].showGridLines = True

        # Write title block on Dashboard
        ws_dash.merge_cells("A1:G1")
        ws_dash["A1"] = f"Financial Statement Analysis Dashboard - {result.ticker}"
        self._style_range(
            ws_dash,
            "A1:G1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="center", vertical="center"),
        )
        ws_dash.row_dimensions[1].height = 30

        # We will write a small data table in A3:G4 (leaving row 2 blank as a separator)
        ws_dash.cell(row=3, column=1, value="Ticker")
        ws_dash.cell(row=3, column=2, value="Piotroski F-Score")
        ws_dash.cell(row=3, column=3, value="P/E Ratio")
        ws_dash.cell(row=3, column=4, value="P/B Ratio")
        ws_dash.cell(row=3, column=5, value="EV/EBITDA")
        ws_dash.cell(row=3, column=6, value="Revenue CAGR (%)")
        ws_dash.cell(row=3, column=7, value="PAT CAGR (%)")

        self._style_range(
            ws_dash,
            "A3:G3",
            font=self.font_data_bold,
            fill=self.fill_alt,
            border=self.border_all,
            alignment=Alignment(horizontal="center"),
        )

        # Write formulas pointing to relevant cells in row 4
        ws_dash.cell(row=4, column=1, value="=Summary!B3")
        ws_dash.cell(row=4, column=2, value="=Health!B2")
        ws_dash.cell(row=4, column=3, value="=Valuation!B2")
        ws_dash.cell(row=4, column=4, value="=Valuation!B3")
        ws_dash.cell(row=4, column=5, value="=Valuation!B4")
        ws_dash.cell(row=4, column=6, value="=Growth!B2*100")
        ws_dash.cell(row=4, column=7, value="=Growth!B3*100")

        self._style_range(
            ws_dash,
            "A4:G4",
            font=self.font_data,
            fill=self.fill_white,
            border=self.border_all,
            alignment=Alignment(horizontal="center"),
        )

        # Adjust column widths for Dashboard sheet
        self._auto_fit_columns(ws_dash)

        # Chart 1: BarChart - Piotroski F score
        chart1 = BarChart()
        chart1.type = "col"
        chart1.title = "Piotroski F-Score Comparison"
        chart1.y_axis.title = "F-Score"
        chart1.x_axis.title = "Ticker"
        chart1.legend = None

        cats = Reference(ws_dash, min_col=1, min_row=4, max_row=4)
        data_f = Reference(ws_dash, min_col=2, min_row=3, max_row=4)
        chart1.add_data(data_f, titles_from_data=True)
        chart1.set_categories(cats)

        # Set color based on value: green if >= 7, orange if 5-6, red if < 5
        f_val = result.health.piotroski_f
        if f_val is not None:
            if f_val >= 7:
                f_color = "28A745"  # green
            elif f_val >= 5:
                f_color = "FD7E14"  # orange
            else:
                f_color = "DC3545"  # red
        else:
            f_color = "CCCCCC"

        if len(chart1.series) > 0:
            chart1.series[0].graphicalProperties.solidFill = f_color

        # Chart 2: BarChart - P/E, P/B, EV/EBITDA
        chart2 = BarChart()
        chart2.type = "col"
        chart2.title = "Valuation Comparison (P/E, P/B, EV/EBITDA)"
        chart2.x_axis.title = "Metric"
        chart2.y_axis.title = "Value"

        cats2 = Reference(ws_dash, min_col=3, max_col=5, min_row=3, max_row=3)
        data2 = Reference(ws_dash, min_col=3, max_col=5, min_row=4, max_row=4)
        chart2.add_data(data2, from_rows=True)
        chart2.set_categories(cats2)
        if len(chart2.series) > 0:
            chart2.series[0].title = SeriesLabel(strRef=StrRef(f="Dashboard!$A$4"))
            chart2.series[0].graphicalProperties.solidFill = "6366F1"  # Indigo

        # Chart 3: BarChart - Revenue CAGR and PAT CAGR
        chart3 = BarChart()
        chart3.type = "col"
        chart3.title = "Growth CAGR Comparison (%)"
        chart3.x_axis.title = "Metric"
        chart3.y_axis.title = "Percentage (%)"

        cats3 = Reference(ws_dash, min_col=6, max_col=7, min_row=3, max_row=3)
        data3 = Reference(ws_dash, min_col=6, max_col=7, min_row=4, max_row=4)
        chart3.add_data(data3, from_rows=True)
        chart3.set_categories(cats3)
        if len(chart3.series) > 0:
            chart3.series[0].title = SeriesLabel(strRef=StrRef(f="Dashboard!$A$4"))
            chart3.series[0].graphicalProperties.solidFill = "10B981"  # Emerald

        # Fetch raw financials to construct line chart for margin trend if multiple periods available
        from telmus.core.loaders import load_financials
        from telmus.core.engines.health import _get_series_fallback

        chart4 = None
        chart5 = None
        chart6 = None
        row_idx = 4
        try:
            financials = load_financials(result.ticker)
            income_stmt = financials.get("income_stmt")
            if income_stmt is not None:
                operating_income = _get_series_fallback(
                    income_stmt, ["Operating Income", "OperatingIncome", "Ebit", "EBIT"]
                )
                revenue = _get_series_fallback(
                    income_stmt, ["Total Revenue", "TotalRevenue", "Revenue"]
                )

                if operating_income is not None and revenue is not None:
                    # Write margin trend table to Dashboard sheet in Columns K and L
                    # We will sort years ascending so the line chart flows correctly
                    unsorted_data = []
                    for col in revenue.index:
                        try:
                            rev_val = float(revenue.loc[col])
                            op_val = float(operating_income.loc[col])
                            if rev_val != 0:
                                margin_pct = (op_val / rev_val) * 100.0
                                year_str = (
                                    str(col.year)
                                    if hasattr(col, "year")
                                    else str(col)[:4]
                                )
                                unsorted_data.append((year_str, margin_pct))
                        except Exception:
                            continue

                    # Sort by year ascending
                    unsorted_data.sort(key=lambda x: x[0])

                    if unsorted_data:
                        ws_dash.cell(row=3, column=11, value="Year")
                        ws_dash.cell(row=3, column=12, value="Margin (%)")
                        self._style_range(
                            ws_dash,
                            "K3:L3",
                            font=self.font_data_bold,
                            fill=self.fill_alt,
                            border=self.border_all,
                            alignment=Alignment(horizontal="center"),
                        )

                        for yr, mrg in unsorted_data:
                            ws_dash.cell(row=row_idx, column=11, value=yr)
                            ws_dash.cell(row=row_idx, column=12, value=mrg)
                            row_idx += 1

                        self._style_range(
                            ws_dash,
                            f"K4:L{row_idx - 1}",
                            font=self.font_data,
                            fill=self.fill_white,
                            border=self.border_all,
                            alignment=Alignment(horizontal="center"),
                        )

                        # Set up LineChart
                        chart4 = LineChart()
                        chart4.title = "Operating Margin Trend (%)"
                        chart4.y_axis.title = "Margin (%)"
                        chart4.x_axis.title = "Year"
                        chart4.legend = None

                        cats4 = Reference(
                            ws_dash, min_col=11, min_row=4, max_row=row_idx - 1
                        )
                        data4 = Reference(
                            ws_dash, min_col=12, min_row=3, max_row=row_idx - 1
                        )
                        chart4.add_data(data4, titles_from_data=True)
                        chart4.set_categories(cats4)

                        if len(chart4.series) > 0:
                            chart4.series[
                                0
                            ].graphicalProperties.line.solidFill = "3B82F6"  # Blue

                        # Chart 5: Revenue History
                        chart5 = BarChart()
                        chart5.type = "col"
                        chart5.title = "Revenue History"
                        chart5.y_axis.title = "Revenue"
                        chart5.x_axis.title = "Year"
                        chart5.legend = None

                        rev_data = []
                        for col in revenue.index:
                            try:
                                r_val = float(revenue.loc[col])
                                y_str = (
                                    str(col.year)
                                    if hasattr(col, "year")
                                    else str(col)[:4]
                                )
                                rev_data.append((y_str, r_val))
                            except Exception:
                                pass
                        rev_data.sort(key=lambda x: x[0])

                        if rev_data:
                            ws_dash.cell(row=3, column=14, value="Year")
                            ws_dash.cell(row=3, column=15, value="Revenue")
                            self._style_range(
                                ws_dash,
                                "N3:O3",
                                font=self.font_data_bold,
                                fill=self.fill_alt,
                                border=self.border_all,
                                alignment=Alignment(horizontal="center"),
                            )
                            r_idx = 4
                            for yr, rval in rev_data:
                                ws_dash.cell(row=r_idx, column=14, value=yr)
                                ws_dash.cell(row=r_idx, column=15, value=rval)
                                r_idx += 1
                            self._style_range(
                                ws_dash,
                                f"N4:O{r_idx - 1}",
                                font=self.font_data,
                                fill=self.fill_white,
                                border=self.border_all,
                                alignment=Alignment(horizontal="center"),
                            )
                            cats5 = Reference(
                                ws_dash, min_col=14, min_row=4, max_row=r_idx - 1
                            )
                            data5 = Reference(
                                ws_dash, min_col=15, min_row=3, max_row=r_idx - 1
                            )
                            chart5.add_data(data5, titles_from_data=True)
                            chart5.set_categories(cats5)
                            if len(chart5.series) > 0:
                                chart5.series[
                                    0
                                ].graphicalProperties.solidFill = "10B981"

                        # Chart 6: P/E History
                        # Fetch price history to calculate P/E
                        chart6 = LineChart()
                        chart6.title = "P/E History"
                        chart6.y_axis.title = "P/E Ratio"
                        chart6.x_axis.title = "Year"
                        chart6.legend = None

                        pe_data = []
                        try:
                            import yfinance as yf

                            hist = yf.Ticker(result.ticker).history(period="5y")
                            eps_series = _get_series_fallback(
                                income_stmt, ["Basic EPS", "Diluted EPS"]
                            )
                            if eps_series is not None and not hist.empty:
                                hist["Year"] = hist.index.year
                                last_prices = hist.groupby("Year")["Close"].last()
                                for col in eps_series.index:
                                    y_str = (
                                        int(col.year)
                                        if hasattr(col, "year")
                                        else int(str(col)[:4])
                                    )
                                    eps_val = float(eps_series.loc[col])
                                    if eps_val > 0 and y_str in last_prices:
                                        pe_val = last_prices[y_str] / eps_val
                                        pe_data.append((str(y_str), pe_val))
                        except Exception:
                            pass

                        pe_data.sort(key=lambda x: x[0])
                        if pe_data:
                            ws_dash.cell(row=3, column=17, value="Year")
                            ws_dash.cell(row=3, column=18, value="P/E")
                            self._style_range(
                                ws_dash,
                                "Q3:R3",
                                font=self.font_data_bold,
                                fill=self.fill_alt,
                                border=self.border_all,
                                alignment=Alignment(horizontal="center"),
                            )
                            p_idx = 4
                            for yr, pval in pe_data:
                                ws_dash.cell(row=p_idx, column=17, value=yr)
                                ws_dash.cell(row=p_idx, column=18, value=pval)
                                p_idx += 1
                            self._style_range(
                                ws_dash,
                                f"Q4:R{p_idx - 1}",
                                font=self.font_data,
                                fill=self.fill_white,
                                border=self.border_all,
                                alignment=Alignment(horizontal="center"),
                            )
                            cats6 = Reference(
                                ws_dash, min_col=17, min_row=4, max_row=p_idx - 1
                            )
                            data6 = Reference(
                                ws_dash, min_col=18, min_row=3, max_row=p_idx - 1
                            )
                            chart6.add_data(data6, titles_from_data=True)
                            chart6.set_categories(cats6)
                            if len(chart6.series) > 0:
                                chart6.series[
                                    0
                                ].graphicalProperties.line.solidFill = "F59E0B"

        except Exception as e:
            logger.warning("Failed to fetch financials for Excel line chart: %s", e)

        # Add charts to Dashboard in a 2x2 grid layout
        ws_dash.add_chart(chart1, "B6")
        ws_dash.add_chart(chart2, "J6")
        ws_dash.add_chart(chart3, "B22")
        if chart4 is not None:
            ws_dash.add_chart(chart4, "J22")
        if chart5 is not None:
            ws_dash.add_chart(chart5, "B38")
        if chart6 is not None:
            ws_dash.add_chart(chart6, "J38")

        # Adjust column widths for Dashboard sheet (re-run to fit K/L column width too)
        self._auto_fit_columns(ws_dash)

        wb.save(path)

    def export_compare(self, result: CompareResult, path: str) -> None:
        wb = Workbook()
        ws = wb.active
        ws.title = "Side by side comparison"
        ws.views.sheetView[0].showGridLines = True

        ticker_a = result.ticker_a
        ticker_b = result.ticker_b

        ws.append(["Metric", f"{ticker_a} Value", f"{ticker_b} Value", "Winner"])
        self._style_range(
            ws,
            "A1:D1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        res_a = result.result_a
        res_b = result.result_b

        metrics = [
            ("P/E Ratio", res_a.valuation.pe_ratio, res_b.valuation.pe_ratio),
            ("P/B Ratio", res_a.valuation.pb_ratio, res_b.valuation.pb_ratio),
            ("EV/EBITDA", res_a.valuation.ev_ebitda, res_b.valuation.ev_ebitda),
            ("Piotroski F-Score", res_a.health.piotroski_f, res_b.health.piotroski_f),
            ("Altman Z-Score", res_a.health.altman_z, res_b.health.altman_z),
            ("Debt / Equity", res_a.health.debt_to_equity, res_b.health.debt_to_equity),
            ("Current Ratio", res_a.health.current_ratio, res_b.health.current_ratio),
            (
                "Interest Coverage",
                res_a.health.interest_coverage,
                res_b.health.interest_coverage,
            ),
            (
                "Revenue CAGR 3Y",
                res_a.growth.revenue_cagr_3y,
                res_b.growth.revenue_cagr_3y,
            ),
            ("PAT CAGR 3Y", res_a.growth.pat_cagr_3y, res_b.growth.pat_cagr_3y),
            ("FCF Yield", res_a.growth.fcf_yield, res_b.growth.fcf_yield),
        ]

        for idx, (m, val_a, val_b) in enumerate(metrics, start=2):
            fill = self.fill_alt if idx % 2 == 1 else self.fill_white

            win_code, win_text = self._get_winner_details(
                m, val_a, val_b, ticker_a, ticker_b
            )

            ws.cell(row=idx, column=1, value=m)
            ws.cell(row=idx, column=2, value=self._val(val_a))
            ws.cell(row=idx, column=3, value=self._val(val_b))
            ws.cell(row=idx, column=4, value=win_text)

            self._style_cell(
                ws.cell(row=idx, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            fill_a = self.fill_green_light if win_code == "A" else fill
            fill_b = self.fill_green_light if win_code == "B" else fill

            self._style_cell(
                ws.cell(row=idx, column=2),
                font=self.font_data,
                fill=fill_a,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )
            self._style_cell(
                ws.cell(row=idx, column=3),
                font=self.font_data,
                fill=fill_b,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            win_fill = self.fill_green_light if win_code in ("A", "B") else fill
            self._style_cell(
                ws.cell(row=idx, column=4),
                font=self.font_data_bold,
                fill=win_fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

        self._auto_fit_columns(ws)
        wb.save(path)

    def _get_winner_details(
        self,
        metric_name: str,
        val_a: typing.Any,
        val_b: typing.Any,
        ticker_a: str,
        ticker_b: str,
    ) -> tuple[str | None, str]:
        if val_a is None and val_b is None:
            return None, "Draw"
        if val_a is None:
            return "B", ticker_b
        if val_b is None:
            return "A", ticker_a

        try:
            a = float(val_a)
            b = float(val_b)
        except (TypeError, ValueError):
            return None, "Draw"

        lower_better = ["P/E Ratio", "P/B Ratio", "EV/EBITDA", "Debt / Equity"]
        is_lower_better = any(lb.lower() in metric_name.lower() for lb in lower_better)

        if a == b:
            return None, "Tie"

        if is_lower_better:
            if "ratio" in metric_name.lower() or "ebitda" in metric_name.lower():
                if a < 0 and b >= 0:
                    return "B", ticker_b
                if b < 0 and a >= 0:
                    return "A", ticker_a
            return ("A", ticker_a) if a < b else ("B", ticker_b)
        else:
            return ("A", ticker_a) if a > b else ("B", ticker_b)

    def export_screen(self, results: list[ScanResult], path: str) -> None:
        wb = Workbook()
        ws = wb.active
        ws.title = "Screening Results"
        ws.views.sheetView[0].showGridLines = True

        headers = [
            "Ticker",
            "Company",
            "P/E",
            "P/B",
            "EV/EBITDA",
            "Piotroski F",
            "Altman Z",
            "Revenue CAGR",
            "Margin Trend",
            "Highest Concern",
        ]
        ws.append(headers)
        self._style_range(
            ws,
            "A1:J1",
            font=self.font_header,
            fill=self.fill_header,
            border=self.border_all,
            alignment=Alignment(horizontal="left"),
        )

        pe_vals, pb_vals, ev_vals, pio_vals, alt_vals, rev_vals = [], [], [], [], [], []

        for idx, r in enumerate(results, start=2):
            fill = self.fill_alt if idx % 2 == 1 else self.fill_white

            ws.cell(row=idx, column=1, value=r.ticker)
            ws.cell(row=idx, column=2, value=r.company)
            ws.cell(row=idx, column=3, value=self._val(r.valuation.pe_ratio))
            ws.cell(row=idx, column=4, value=self._val(r.valuation.pb_ratio))
            ws.cell(row=idx, column=5, value=self._val(r.valuation.ev_ebitda))
            ws.cell(row=idx, column=6, value=self._val(r.health.piotroski_f))
            ws.cell(row=idx, column=7, value=self._val(r.health.altman_z))
            ws.cell(row=idx, column=8, value=self._val(r.growth.revenue_cagr_3y))
            ws.cell(row=idx, column=9, value=r.growth.margin_trend or "n/a")
            ws.cell(row=idx, column=10, value=r.highest_concern)

            for col_idx in range(1, 10):
                self._style_cell(
                    ws.cell(row=idx, column=col_idx),
                    font=self.font_data,
                    fill=fill,
                    border=self.border_all,
                    alignment=Alignment(horizontal="left"),
                )
            self._style_cell(
                ws.cell(row=idx, column=1),
                font=self.font_data_bold,
                fill=fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            c_val = str(r.highest_concern).lower()
            if "high" in c_val:
                c_fill = self.fill_red_light
            elif "medium" in c_val:
                c_fill = self.fill_orange_light
            else:
                c_fill = self.fill_green_light
            self._style_cell(
                ws.cell(row=idx, column=10),
                font=self.font_data_bold,
                fill=c_fill,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

            if r.valuation.pe_ratio is not None:
                pe_vals.append(r.valuation.pe_ratio)
            if r.valuation.pb_ratio is not None:
                pb_vals.append(r.valuation.pb_ratio)
            if r.valuation.ev_ebitda is not None:
                ev_vals.append(r.valuation.ev_ebitda)
            if r.health.piotroski_f is not None:
                pio_vals.append(r.health.piotroski_f)
            if r.health.altman_z is not None:
                alt_vals.append(r.health.altman_z)
            if r.growth.revenue_cagr_3y is not None:
                rev_vals.append(r.growth.revenue_cagr_3y)

        tot_row = len(results) + 2

        def avg(vals: list[float]) -> float | str:
            return round(sum(vals) / len(vals), 2) if vals else "n/a"

        ws.cell(row=tot_row, column=1, value="Average")
        ws.cell(row=tot_row, column=2, value="")
        ws.cell(row=tot_row, column=3, value=avg(pe_vals))
        ws.cell(row=tot_row, column=4, value=avg(pb_vals))
        ws.cell(row=tot_row, column=5, value=avg(ev_vals))
        ws.cell(row=tot_row, column=6, value=avg(pio_vals))
        ws.cell(row=tot_row, column=7, value=avg(alt_vals))
        ws.cell(row=tot_row, column=8, value=avg(rev_vals))
        ws.cell(row=tot_row, column=9, value="")
        ws.cell(row=tot_row, column=10, value="")

        for col_idx in range(1, 11):
            cell = ws.cell(row=tot_row, column=col_idx)
            self._style_cell(
                cell,
                font=self.font_data_bold,
                fill=self.fill_alt,
                border=self.border_all,
                alignment=Alignment(horizontal="left"),
            )

        self._auto_fit_columns(ws)
        wb.save(path)
